<script>
    require([
        'jquery',
        'owlCarousel'
        ], function ($) {
            $(document).ready(function() {
                var owl = $('.owl-carousel-dropdownmenu');
                owl.owlCarousel({
                    items: 1,
                    loop: true,
                    // autoplay: true,
                    // autoplayTimeout: 1000,
                    autoplayHoverPause: true,
                    dots:false,
                    nav: true,
                    navText: [
                    "<i class='fa fa-caret-left'></i>",
                    "<i class='fas fa-chevron-right'></i>"
                    ],

                });
            });
        });
    </script>