<div data-mage-init="{&quot;accordion&quot;:{&quot;openedState&quot;: &quot;active&quot;, &quot;collapsible&quot;: true, &quot;active&quot;: false, &quot;multipleCollapsible&quot;: &quot;true&quot;}}">
 
  <div data-role="collapsible">
    <div class="footer-title-mobile" data-role="trigger">Categories</div>
  </div>
  <div data-role="content">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-category-link')->toHtml();?>    
  </div>
</div>
<script>
    require([
        'jquery',
        'accordion'], function ($) {
        $("#element").accordion();
    });
</script>