<div data-mage-init="{&quot;accordion&quot;:{&quot;openedState&quot;: &quot;active&quot;, &quot;collapsible&quot;: true, &quot;active&quot;: false, &quot;multipleCollapsible&quot;: &quot;true&quot;}}">
 
  <div data-role="collapsible">
    <div class="footer-title-mobile" data-role="trigger">Our Policies</div>
  </div>
  <div data-role="content">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-link2')->toHtml();?>    
  </div>
</div>