<div class="header-top-destop">
	<?php
	echo $block->getLayout()

	->createBlock('Magento\Cms\Block\Block')

	->setBlockId('header-top-left')

	->toHtml();

	?>
</div>
<div class="header-top-destop">	
	<?php
	echo $block->getLayout()

	->createBlock('Magento\Cms\Block\Block')

	->setBlockId('header-top-center')

	->toHtml();

	?>
</div>
<div class="header-top-mobile">
	<?php
	echo $block->getLayout()

	->createBlock('Magento\Cms\Block\Block')

	->setBlockId('header-top-mobile')

	->toHtml();
	?>
</div>