    <?php for( $i = 1; $i <= 3; $i++){ ?>
        <div class="item">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner-center-img-'.$i.'')->toHtml();
                  echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner-center-text-'.$i.'')->toHtml();
                ?>
            <button>shop now <i class="fas fa-chevron-right"></i></button>
        </div>
    <?php } ?>