<div class="reason-buy">
<?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner-resson-to-buy')->toHtml();?>
</div>
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".reason-buy").not('.slick-initialized').slick({
                dot: false,
				infinite: true,
				slidesToShow: 3,
				slidesToScroll: 3,
				arrows: false,
				swipeToSlide: true,
				responsive: [
				{
					breakpoint: 769,
					settings: {
						slidesToShow: 1,
						slidesToScroll: 1
					}
				},
				{
					breakpoint: 1025,
					settings: {
						slidesToShow: 2,
						slidesToScroll: 2
					}
				}
				]
            });
        });
    });
</script>