<div class="productproductgroup">
    <div class="productproductgroup__top">
        <div>
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('group-button-roy')->toHtml();?>
        </div>
        <div>
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('group-button-sun')->toHtml();?>
        </div>
    </div>
    <div class="productproductgroup__bottom">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('group-button-big')->toHtml();?>
    </div>
</div>